namespace EpubReader.Application.Services;

internal static class Catalog
{
    public static string? TryGet(string culture, string key)
    {
        var map = culture.Equals("pl", StringComparison.OrdinalIgnoreCase) ? Pl : En;
        return map.TryGetValue(key, out var value) ? value : null;
    }

    private static readonly Dictionary<string, string> En = new(StringComparer.Ordinal)
    {
        ["app.noBook"] = "No book loaded",
        ["app.toc"] = "Table of contents (T)",
        ["app.open"] = "Open",
        ["app.openTitle"] = "Open EPUB (Ctrl+O)",
        ["app.demo"] = "Demo",
        ["app.appearance"] = "Appearance",
        ["app.search"] = "Search (/)",
        ["app.bookmarks"] = "Bookmarks (B)",
        ["app.info"] = "Info",
        ["app.ttsPlay"] = "Read chapter (R)",
        ["app.ttsPause"] = "Pause (R)",
        ["app.ttsResume"] = "Resume (R)",
        ["app.ttsStop"] = "Stop TTS",
        ["app.ttsBack"] = "Rewind ( [ )",
        ["app.ttsForward"] = "Skip forward ( ] )",
        ["app.ttsSlower"] = "Slower",
        ["app.ttsFaster"] = "Faster",

        ["settings.title"] = "Reader settings",
        ["settings.theme"] = "Theme",
        ["settings.font"] = "Font",
        ["settings.fontSize"] = "Font size",
        ["settings.lineHeight"] = "Line height",
        ["settings.letterSpacing"] = "Letter spacing",
        ["settings.paragraphSpacing"] = "Paragraph spacing",
        ["settings.align"] = "Alignment",
        ["settings.alignLeft"] = "Left",
        ["settings.alignJustify"] = "Justify",
        ["settings.alignCenter"] = "Center",
        ["settings.width"] = "Column width",
        ["settings.margin"] = "Page margin",
        ["settings.infiniteScroll"] = "Infinite scroll",
        ["settings.infiniteScrollHint"] = "Keep scrolling well past the chapter to go next or previous. Needs a large extra swipe so it is not accidental.",
        ["viewport.infiniteNext"] = "Keep scrolling for the next chapter",
        ["viewport.infinitePrev"] = "Keep scrolling for the previous chapter",
        ["settings.tts"] = "Read aloud",
        ["settings.ttsEngine"] = "Engine",
        ["settings.ttsEngineHint"] = "Edge = online neural. Piper = offline EN neural (Windows/Android app). System = OS voices.",
        ["settings.ttsEngineHintWeb"] = "Web: Edge, or System voices. Piper - the Windows/Android app.",
        ["settings.ttsEngineHintWebNoEdge"] = "Web uses System (browser) voices. Edge neural needs the desktop/Android app — browsers block its WebSocket.",
        ["settings.ttsRate"] = "Rate",
        ["settings.restoreScroll"] = "Remember scroll position",
        ["settings.restoreScrollHint"] = "Jump back to where you left off in the chapter.",
        ["settings.restoreTts"] = "Remember read-aloud position",
        ["settings.restoreTtsHint"] = "Resume TTS from the last chunk after stop or relaunch.",
        ["settings.ttsAutoNext"] = "Auto next chapter",
        ["settings.ttsAutoNextHint"] = "When reading finishes, go to the next chapter.",
        ["settings.ttsAutoPlay"] = "Auto-read next chapter",
        ["settings.ttsAutoPlayHint"] = "Keep reading aloud after auto-next (continuous audiobook mode).",
        ["settings.ttsVoiceLang"] = "Voice language",
        ["settings.ttsLangAuto"] = "Auto (detect)",
        ["settings.ttsLangPiperLocked"] = "Piper voices are English-only. Your previous language setting is kept and restored when you leave Piper.",
        ["settings.piperOptions"] = "Piper voice",
        ["settings.piperVoice"] = "English voice",
        ["settings.piperStatus"] = "Status",
        ["settings.piperReady"] = "Ready",
        ["settings.piperNotDownloaded"] = "Not downloaded yet",
        ["settings.piperDownloadingRuntime"] = "Downloading Piper runtime…",
        ["settings.piperDownloadingVoice"] = "Downloading voice…",
        ["settings.piperExtracting"] = "Extracting…",
        ["settings.piperError"] = "Download failed",
        ["settings.piperHint"] = "First use downloads the selected voice offline. Switching voices may download another model.",
        ["settings.uiLanguage"] = "App language",
        ["settings.uiLangAuto"] = "System",
        ["settings.uiLangEn"] = "English",
        ["settings.uiLangPl"] = "Polish",

        ["theme.light"] = "Light",
        ["theme.sepia"] = "Sepia",
        ["theme.paper"] = "Paper",
        ["theme.dark"] = "Dark",
        ["theme.nord"] = "Nord",
        ["theme.forest"] = "Forest",
        ["theme.rose"] = "Rose",
        ["theme.midnight"] = "Midnight",
        ["theme.solarized"] = "Solar",
        ["theme.oled"] = "OLED",

        ["toc.title"] = "Contents",
        ["toc.hide"] = "Hide (T)",
        ["toc.filter"] = "Filter chapters…",
        ["toc.chapters"] = "{0} chapters · TOC {1}",
        ["toc.empty"] = "Load an EPUB to see navigation.",
        ["toc.progress"] = "Progress",

        ["viewport.drop"] = "Drop EPUB file here",
        ["viewport.loading"] = "Loading EPUB…",
        ["viewport.retry"] = "Try again",
        ["viewport.readyTitle"] = "Ready to read",
        ["viewport.readyBody"] = "Open an EPUB, drag a file onto the window, or run the demo. Shortcuts: Ctrl+O open, T contents, / search.",
        ["viewport.pickFile"] = "Choose EPUB file",
        ["viewport.tryDemo"] = "Try demo",
        ["viewport.bookmark"] = "Bookmark",
        ["viewport.prev"] = "Previous",
        ["viewport.next"] = "Next",
        ["viewport.fontDown"] = "Decrease font",
        ["viewport.fontUp"] = "Increase font",

        ["search.title"] = "Search in book",
        ["search.placeholder"] = "Enter a phrase…",
        ["search.button"] = "Search",
        ["search.needBook"] = "Load a book first.",
        ["search.hint"] = "Enter a keyword above.",
        ["search.none"] = "No results for \"{0}\".",

        ["bookmarks.title"] = "Saved bookmarks",
        ["bookmarks.empty"] = "No saved bookmarks.",
        ["bookmarks.chapter"] = "Chapter {0}",

        ["meta.cover"] = "Cover",
        ["meta.title"] = "Title",
        ["meta.author"] = "Author",
        ["meta.language"] = "Language",
        ["meta.publisher"] = "Publisher",
        ["meta.publisherNone"] = "N/A",
        ["meta.chapters"] = "Chapters",
        ["meta.description"] = "Description",
        ["meta.descriptionNone"] = "No description.",
        ["meta.infoTitle"] = "Publication info",
        ["meta.shortcuts"] = "Shortcuts: ←/→ chapter · J/K or Space page · T contents · / search · B bookmark · R read aloud · [ ] rewind/skip · F hide chrome · Esc close",

        ["status.parsing"] = "Parsing EPUB…",
        ["status.loaded"] = "Loaded {0} chapters",
        ["status.restoring"] = "Restoring last book…",
        ["status.restored"] = "Restored “{0}”",
        ["status.externalLink"] = "Opened external link",
        ["status.goto"] = "Go to: {0}",
        ["status.chapterMissing"] = "Target chapter not found",
        ["status.bookmarkAdded"] = "Bookmark added",
        ["status.bookmarkRemoved"] = "Bookmark removed",
        ["status.epubOnly"] = "Only .epub files are supported",

        ["tts.noText"] = "No text to read",
        ["tts.noEngine"] = "No TTS engine available",
        ["tts.playing"] = "TTS ({0}) · {1}",
        ["tts.done"] = "Reading finished",
        ["tts.edgeFallback"] = "Edge neural unavailable — switching to system",
        ["tts.error"] = "TTS: {0}",
        ["tts.resumed"] = "Resumed",
        ["tts.paused"] = "Paused",
        ["tts.edgeUnavailableNote"] = "Edge neural unavailable — using system",
        ["tts.chunkProgress"] = "{0} {1}/{2}",
        ["tts.engineEdge"] = "Edge",
        ["tts.engineSystem"] = "System",
        ["tts.engineFallback"] = "System (Edge↓)",
        ["tts.enginePiper"] = "Piper",
        ["tts.piperPreparing"] = "Piper: downloading EN voice (first run)…",
        ["tts.piperUnavailableNote"] = "Piper unavailable — using system",
        ["tts.piperFallback"] = "Edge unavailable — switching to Piper",
    };

    private static readonly Dictionary<string, string> Pl = new(StringComparer.Ordinal)
    {
        ["app.noBook"] = "Nie załadowano książki",
        ["app.toc"] = "Spis treści (T)",
        ["app.open"] = "Otwórz",
        ["app.openTitle"] = "Otwórz EPUB (Ctrl+O)",
        ["app.demo"] = "Demo",
        ["app.appearance"] = "Wygląd",
        ["app.search"] = "Szukaj (/)",
        ["app.bookmarks"] = "Zakładki (B)",
        ["app.info"] = "Info",
        ["app.ttsPlay"] = "Czytaj rozdział (R)",
        ["app.ttsPause"] = "Pauza (R)",
        ["app.ttsResume"] = "Wznów odczyt (R)",
        ["app.ttsStop"] = "Stop TTS",
        ["app.ttsBack"] = "Wstecz ( [ )",
        ["app.ttsForward"] = "Dalej ( ] )",
        ["app.ttsSlower"] = "Wolniej",
        ["app.ttsFaster"] = "Szybciej",

        ["settings.title"] = "Ustawienia czytnika",
        ["settings.theme"] = "Motyw",
        ["settings.font"] = "Czcionka",
        ["settings.fontSize"] = "Rozmiar tekstu",
        ["settings.lineHeight"] = "Interlinia",
        ["settings.letterSpacing"] = "Odstępy liter",
        ["settings.paragraphSpacing"] = "Odstęp akapitów",
        ["settings.align"] = "Wyrównanie",
        ["settings.alignLeft"] = "Do lewej",
        ["settings.alignJustify"] = "Justuj",
        ["settings.alignCenter"] = "Środek",
        ["settings.width"] = "Szerokość kolumny",
        ["settings.margin"] = "Margines strony",
        ["settings.infiniteScroll"] = "Infinite scroll",
        ["settings.infiniteScrollHint"] = "Przewiń wyraźnie za koniec (albo początek) rozdziału, żeby przejść dalej. Duży zapas, żeby nie skakało przypadkiem.",
        ["viewport.infiniteNext"] = "Przewiń dalej, aby przejść do następnego rozdziału",
        ["viewport.infinitePrev"] = "Przewiń w górę, aby wrócić do poprzedniego rozdziału",
        ["settings.tts"] = "Czytanie na głos",
        ["settings.ttsEngine"] = "Silnik",
        ["settings.ttsEngineHint"] = "Edge = neural online. Piper = offline EN neural (Windows/Android). System = głosy OS.",
        ["settings.ttsEngineHintWeb"] = "Web: Edge (zawsze włączony) albo System. Piper - Windows/Android.",
        ["settings.ttsEngineHintWebNoEdge"] = "Web używa głosów System (przeglądarka). Edge neural działa w aplikacji — przeglądarka blokuje jego WebSocket.",
        ["settings.ttsRate"] = "Tempo",
        ["settings.restoreScroll"] = "Zapamiętaj pozycję scrolla",
        ["settings.restoreScrollHint"] = "Wracaj w rozdziale tam, gdzie skończyłeś czytać.",
        ["settings.restoreTts"] = "Zapamiętaj pozycję czytania na głos",
        ["settings.restoreTtsHint"] = "Wznawiaj TTS od ostatniego fragmentu po stopie lub restarcie.",
        ["settings.ttsAutoNext"] = "Auto następny rozdział",
        ["settings.ttsAutoNextHint"] = "Po zakończeniu odczytu przejdź do kolejnego rozdziału.",
        ["settings.ttsAutoPlay"] = "Autoczytanie kolejnego",
        ["settings.ttsAutoPlayHint"] = "Po auto-next kontynuuj czytanie na głos (tryb audiobook).",
        ["settings.ttsVoiceLang"] = "Język głosu",
        ["settings.ttsLangAuto"] = "Auto (wykryj)",
        ["settings.ttsLangPiperLocked"] = "Piper obsługuje tylko angielski. Poprzedni język zostaje zapisany i wraca po wyjściu z Pipera.",
        ["settings.piperOptions"] = "Głos Piper",
        ["settings.piperVoice"] = "Głos angielski",
        ["settings.piperStatus"] = "Status",
        ["settings.piperReady"] = "Gotowy",
        ["settings.piperNotDownloaded"] = "Jeszcze nie pobrano",
        ["settings.piperDownloadingRuntime"] = "Pobieranie runtime Piper…",
        ["settings.piperDownloadingVoice"] = "Pobieranie głosu…",
        ["settings.piperExtracting"] = "Rozpakowywanie…",
        ["settings.piperError"] = "Pobieranie nieudane",
        ["settings.piperHint"] = "Przy pierwszym użyciu głos pobiera się offline. Zmiana głosu może pobrać inny model.",
        ["settings.uiLanguage"] = "Język aplikacji",
        ["settings.uiLangAuto"] = "Systemowy",
        ["settings.uiLangEn"] = "English",
        ["settings.uiLangPl"] = "Polski",

        ["theme.light"] = "Jasny",
        ["theme.sepia"] = "Sepia",
        ["theme.paper"] = "Papier",
        ["theme.dark"] = "Ciemny",
        ["theme.nord"] = "Nord",
        ["theme.forest"] = "Las",
        ["theme.rose"] = "Róż",
        ["theme.midnight"] = "Północ",
        ["theme.solarized"] = "Solar",
        ["theme.oled"] = "OLED",

        ["toc.title"] = "Spis treści",
        ["toc.hide"] = "Ukryj (T)",
        ["toc.filter"] = "Filtruj rozdziały…",
        ["toc.chapters"] = "{0} rozdziałów · TOC {1}",
        ["toc.empty"] = "Załaduj plik EPUB, aby zobaczyć nawigację.",
        ["toc.progress"] = "Postęp",

        ["viewport.drop"] = "Upuść plik EPUB tutaj",
        ["viewport.loading"] = "Ładowanie EPUB…",
        ["viewport.retry"] = "Spróbuj ponownie",
        ["viewport.readyTitle"] = "Gotowy do czytania",
        ["viewport.readyBody"] = "Otwórz EPUB, przeciągnij plik na okno albo uruchom demo. Skróty: Ctrl+O otwórz, T spis, / szukaj.",
        ["viewport.pickFile"] = "Wybierz plik EPUB",
        ["viewport.tryDemo"] = "Wypróbuj demo",
        ["viewport.bookmark"] = "Zakładka",
        ["viewport.prev"] = "Poprzedni",
        ["viewport.next"] = "Następny",
        ["viewport.fontDown"] = "Zmniejsz czcionkę",
        ["viewport.fontUp"] = "Zwiększ czcionkę",

        ["search.title"] = "Wyszukiwanie w książce",
        ["search.placeholder"] = "Wpisz frazę…",
        ["search.button"] = "Szukaj",
        ["search.needBook"] = "Najpierw załaduj książkę.",
        ["search.hint"] = "Wpisz słowo kluczowe powyżej.",
        ["search.none"] = "Brak wyników dla \"{0}\".",

        ["bookmarks.title"] = "Zapisane zakładki",
        ["bookmarks.empty"] = "Brak zapisanych zakładek.",
        ["bookmarks.chapter"] = "Rozdział {0}",

        ["meta.cover"] = "Okładka",
        ["meta.title"] = "Tytuł",
        ["meta.author"] = "Autor",
        ["meta.language"] = "Język",
        ["meta.publisher"] = "Wydawca",
        ["meta.publisherNone"] = "Brak danych",
        ["meta.chapters"] = "Liczba rozdziałów",
        ["meta.description"] = "Opis",
        ["meta.descriptionNone"] = "Brak opisu.",
        ["meta.infoTitle"] = "Informacje o publikacji",
        ["meta.shortcuts"] = "Skróty: ←/→ rozdział · J/K lub Spacja strona · T spis · / szukaj · B zakładka · R odczyt · [ ] wstecz/dalej · F ukryj chrome · Esc zamknij",

        ["status.parsing"] = "Parsowanie EPUB…",
        ["status.loaded"] = "Załadowano {0} rozdziałów",
        ["status.restoring"] = "Przywracam ostatnią książkę…",
        ["status.restored"] = "Przywrócono „{0}”",
        ["status.externalLink"] = "Otwarto łącze zewnętrzne",
        ["status.goto"] = "Przejście: {0}",
        ["status.chapterMissing"] = "Nie znaleziono docelowego rozdziału",
        ["status.bookmarkAdded"] = "Dodano zakładkę",
        ["status.bookmarkRemoved"] = "Usunięto zakładkę",
        ["status.epubOnly"] = "Obsługiwane są tylko pliki .epub",

        ["tts.noText"] = "Brak tekstu do odczytu",
        ["tts.noEngine"] = "Brak dostępnego silnika TTS",
        ["tts.playing"] = "TTS ({0}) · {1}",
        ["tts.done"] = "Odczyt zakończony",
        ["tts.edgeFallback"] = "Edge neural niedostępny — przełączam na systemowy",
        ["tts.error"] = "TTS: {0}",
        ["tts.resumed"] = "Wznowiono",
        ["tts.paused"] = "Pauza",
        ["tts.edgeUnavailableNote"] = "Edge neural niedostępny — używam systemowego",
        ["tts.chunkProgress"] = "{0} {1}/{2}",
        ["tts.engineEdge"] = "Edge",
        ["tts.engineSystem"] = "System",
        ["tts.engineFallback"] = "System (Edge↓)",
        ["tts.enginePiper"] = "Piper",
        ["tts.piperPreparing"] = "Piper: pobieram głos EN (pierwszy raz)…",
        ["tts.piperUnavailableNote"] = "Piper niedostępny — używam systemowego",
        ["tts.piperFallback"] = "Edge niedostępny — przełączam na Piper",
    };
}
