namespace EpubReader.Application.Services;

internal static class Catalog
{
    public static string? TryGet(string culture, string key)
    {
        var map = culture.Equals("pl", StringComparison.OrdinalIgnoreCase) ? Pl : En;
        return map.TryGetValue(key, out var value) ? value : null;
    }

    private static readonly Dictionary<string, string> En = new(StringComparer.Ordinal)
    {
        ["app.noBook"] = "No book loaded",
        ["app.toc"] = "Table of contents (T)",
        ["app.open"] = "Open",
        ["app.openTitle"] = "Open EPUB (Ctrl+O)",
        ["app.demo"] = "Demo",
        ["app.appearance"] = "Appearance",
        ["app.search"] = "Search (/)",
        ["app.bookmarks"] = "Bookmarks (B)",
        ["app.info"] = "Info",
        ["app.ttsPlay"] = "Read chapter (R)",
        ["app.ttsPause"] = "Pause (R)",
        ["app.ttsResume"] = "Resume (R)",
        ["app.ttsStop"] = "Stop TTS",
        ["app.ttsBack"] = "Rewind ( [ )",
        ["app.ttsForward"] = "Skip forward ( ] )",
        ["app.ttsSlower"] = "Slower",
        ["app.ttsFaster"] = "Faster",

        ["settings.title"] = "Reader settings",
        ["settings.theme"] = "Theme",
        ["settings.font"] = "Font",
        ["settings.fontSize"] = "Font size",
        ["settings.lineHeight"] = "Line height",
        ["settings.letterSpacing"] = "Letter spacing",
        ["settings.paragraphSpacing"] = "Paragraph spacing",
        ["settings.align"] = "Alignment",
        ["settings.alignLeft"] = "Left",
        ["settings.alignJustify"] = "Justify",
        ["settings.alignCenter"] = "Center",
        ["settings.width"] = "Column width",
        ["settings.margin"] = "Page margin",
        ["settings.tts"] = "Read aloud",
        ["settings.ttsEngine"] = "Engine",
        ["settings.ttsEngineHint"] = "Edge = neural online (best effort). System = OS / browser voices.",
        ["settings.ttsRate"] = "Rate",
        ["settings.ttsVoiceLang"] = "Voice language",
        ["settings.ttsLangAuto"] = "Auto (detect)",
        ["settings.uiLanguage"] = "App language",
        ["settings.uiLangAuto"] = "System",
        ["settings.uiLangEn"] = "English",
        ["settings.uiLangPl"] = "Polish",

        ["theme.light"] = "Light",
        ["theme.sepia"] = "Sepia",
        ["theme.paper"] = "Paper",
        ["theme.dark"] = "Dark",
        ["theme.nord"] = "Nord",
        ["theme.forest"] = "Forest",
        ["theme.rose"] = "Rose",
        ["theme.midnight"] = "Midnight",
        ["theme.solarized"] = "Solar",
        ["theme.oled"] = "OLED",

        ["toc.title"] = "Contents",
        ["toc.hide"] = "Hide (T)",
        ["toc.filter"] = "Filter chapters…",
        ["toc.chapters"] = "{0} chapters · TOC {1}",
        ["toc.empty"] = "Load an EPUB to see navigation.",
        ["toc.progress"] = "Progress",

        ["viewport.drop"] = "Drop EPUB file here",
        ["viewport.loading"] = "Loading EPUB…",
        ["viewport.retry"] = "Try again",
        ["viewport.readyTitle"] = "Ready to read",
        ["viewport.readyBody"] = "Open an EPUB, drag a file onto the window, or run the demo. Shortcuts: Ctrl+O open, T contents, / search.",
        ["viewport.pickFile"] = "Choose EPUB file",
        ["viewport.tryDemo"] = "Try demo",
        ["viewport.bookmark"] = "Bookmark",
        ["viewport.prev"] = "Previous",
        ["viewport.next"] = "Next",
        ["viewport.fontDown"] = "Decrease font",
        ["viewport.fontUp"] = "Increase font",

        ["search.title"] = "Search in book",
        ["search.placeholder"] = "Enter a phrase…",
        ["search.button"] = "Search",
        ["search.needBook"] = "Load a book first.",
        ["search.hint"] = "Enter a keyword above.",
        ["search.none"] = "No results for \"{0}\".",

        ["bookmarks.title"] = "Saved bookmarks",
        ["bookmarks.empty"] = "No saved bookmarks.",
        ["bookmarks.chapter"] = "Chapter {0}",

        ["meta.cover"] = "Cover",
        ["meta.title"] = "Title",
        ["meta.author"] = "Author",
        ["meta.language"] = "Language",
        ["meta.publisher"] = "Publisher",
        ["meta.publisherNone"] = "N/A",
        ["meta.chapters"] = "Chapters",
        ["meta.description"] = "Description",
        ["meta.descriptionNone"] = "No description.",
        ["meta.infoTitle"] = "Publication info",
        ["meta.shortcuts"] = "Shortcuts: ←/→ chapter · J/K or Space page · T contents · / search · B bookmark · R read aloud · [ ] rewind/skip · F hide chrome · Esc close",

        ["status.parsing"] = "Parsing EPUB…",
        ["status.loaded"] = "Loaded {0} chapters",
        ["status.externalLink"] = "Opened external link",
        ["status.goto"] = "Go to: {0}",
        ["status.chapterMissing"] = "Target chapter not found",
        ["status.bookmarkAdded"] = "Bookmark added",
        ["status.bookmarkRemoved"] = "Bookmark removed",

        ["tts.noText"] = "No text to read",
        ["tts.noEngine"] = "No TTS engine available",
        ["tts.playing"] = "TTS ({0}) · {1}",
        ["tts.done"] = "Reading finished",
        ["tts.edgeFallback"] = "Edge neural unavailable — switching to system",
        ["tts.error"] = "TTS: {0}",
        ["tts.resumed"] = "Resumed",
        ["tts.paused"] = "Paused",
        ["tts.edgeUnavailableNote"] = "Edge neural unavailable — using system",
        ["tts.chunkProgress"] = "{0} {1}/{2}",
        ["tts.engineEdge"] = "Edge",
        ["tts.engineSystem"] = "System",
        ["tts.engineFallback"] = "System (Edge↓)",
    };

    private static readonly Dictionary<string, string> Pl = new(StringComparer.Ordinal)
    {
        ["app.noBook"] = "Nie załadowano książki",
        ["app.toc"] = "Spis treści (T)",
        ["app.open"] = "Otwórz",
        ["app.openTitle"] = "Otwórz EPUB (Ctrl+O)",
        ["app.demo"] = "Demo",
        ["app.appearance"] = "Wygląd",
        ["app.search"] = "Szukaj (/)",
        ["app.bookmarks"] = "Zakładki (B)",
        ["app.info"] = "Info",
        ["app.ttsPlay"] = "Czytaj rozdział (R)",
        ["app.ttsPause"] = "Pauza (R)",
        ["app.ttsResume"] = "Wznów odczyt (R)",
        ["app.ttsStop"] = "Stop TTS",
        ["app.ttsBack"] = "Wstecz ( [ )",
        ["app.ttsForward"] = "Dalej ( ] )",
        ["app.ttsSlower"] = "Wolniej",
        ["app.ttsFaster"] = "Szybciej",

        ["settings.title"] = "Ustawienia czytnika",
        ["settings.theme"] = "Motyw",
        ["settings.font"] = "Czcionka",
        ["settings.fontSize"] = "Rozmiar tekstu",
        ["settings.lineHeight"] = "Interlinia",
        ["settings.letterSpacing"] = "Odstępy liter",
        ["settings.paragraphSpacing"] = "Odstęp akapitów",
        ["settings.align"] = "Wyrównanie",
        ["settings.alignLeft"] = "Do lewej",
        ["settings.alignJustify"] = "Justuj",
        ["settings.alignCenter"] = "Środek",
        ["settings.width"] = "Szerokość kolumny",
        ["settings.margin"] = "Margines strony",
        ["settings.tts"] = "Czytanie na głos",
        ["settings.ttsEngine"] = "Silnik",
        ["settings.ttsEngineHint"] = "Edge = neural online (best effort). System = głosy OS / przeglądarki.",
        ["settings.ttsRate"] = "Tempo",
        ["settings.ttsVoiceLang"] = "Język głosu",
        ["settings.ttsLangAuto"] = "Auto (wykryj)",
        ["settings.uiLanguage"] = "Język aplikacji",
        ["settings.uiLangAuto"] = "Systemowy",
        ["settings.uiLangEn"] = "English",
        ["settings.uiLangPl"] = "Polski",

        ["theme.light"] = "Jasny",
        ["theme.sepia"] = "Sepia",
        ["theme.paper"] = "Papier",
        ["theme.dark"] = "Ciemny",
        ["theme.nord"] = "Nord",
        ["theme.forest"] = "Las",
        ["theme.rose"] = "Róż",
        ["theme.midnight"] = "Północ",
        ["theme.solarized"] = "Solar",
        ["theme.oled"] = "OLED",

        ["toc.title"] = "Spis treści",
        ["toc.hide"] = "Ukryj (T)",
        ["toc.filter"] = "Filtruj rozdziały…",
        ["toc.chapters"] = "{0} rozdziałów · TOC {1}",
        ["toc.empty"] = "Załaduj plik EPUB, aby zobaczyć nawigację.",
        ["toc.progress"] = "Postęp",

        ["viewport.drop"] = "Upuść plik EPUB tutaj",
        ["viewport.loading"] = "Ładowanie EPUB…",
        ["viewport.retry"] = "Spróbuj ponownie",
        ["viewport.readyTitle"] = "Gotowy do czytania",
        ["viewport.readyBody"] = "Otwórz EPUB, przeciągnij plik na okno albo uruchom demo. Skróty: Ctrl+O otwórz, T spis, / szukaj.",
        ["viewport.pickFile"] = "Wybierz plik EPUB",
        ["viewport.tryDemo"] = "Wypróbuj demo",
        ["viewport.bookmark"] = "Zakładka",
        ["viewport.prev"] = "Poprzedni",
        ["viewport.next"] = "Następny",
        ["viewport.fontDown"] = "Zmniejsz czcionkę",
        ["viewport.fontUp"] = "Zwiększ czcionkę",

        ["search.title"] = "Wyszukiwanie w książce",
        ["search.placeholder"] = "Wpisz frazę…",
        ["search.button"] = "Szukaj",
        ["search.needBook"] = "Najpierw załaduj książkę.",
        ["search.hint"] = "Wpisz słowo kluczowe powyżej.",
        ["search.none"] = "Brak wyników dla \"{0}\".",

        ["bookmarks.title"] = "Zapisane zakładki",
        ["bookmarks.empty"] = "Brak zapisanych zakładek.",
        ["bookmarks.chapter"] = "Rozdział {0}",

        ["meta.cover"] = "Okładka",
        ["meta.title"] = "Tytuł",
        ["meta.author"] = "Autor",
        ["meta.language"] = "Język",
        ["meta.publisher"] = "Wydawca",
        ["meta.publisherNone"] = "Brak danych",
        ["meta.chapters"] = "Liczba rozdziałów",
        ["meta.description"] = "Opis",
        ["meta.descriptionNone"] = "Brak opisu.",
        ["meta.infoTitle"] = "Informacje o publikacji",
        ["meta.shortcuts"] = "Skróty: ←/→ rozdział · J/K lub Spacja strona · T spis · / szukaj · B zakładka · R odczyt · [ ] wstecz/dalej · F ukryj chrome · Esc zamknij",

        ["status.parsing"] = "Parsowanie EPUB…",
        ["status.loaded"] = "Załadowano {0} rozdziałów",
        ["status.externalLink"] = "Otwarto łącze zewnętrzne",
        ["status.goto"] = "Przejście: {0}",
        ["status.chapterMissing"] = "Nie znaleziono docelowego rozdziału",
        ["status.bookmarkAdded"] = "Dodano zakładkę",
        ["status.bookmarkRemoved"] = "Usunięto zakładkę",

        ["tts.noText"] = "Brak tekstu do odczytu",
        ["tts.noEngine"] = "Brak dostępnego silnika TTS",
        ["tts.playing"] = "TTS ({0}) · {1}",
        ["tts.done"] = "Odczyt zakończony",
        ["tts.edgeFallback"] = "Edge neural niedostępny — przełączam na systemowy",
        ["tts.error"] = "TTS: {0}",
        ["tts.resumed"] = "Wznowiono",
        ["tts.paused"] = "Pauza",
        ["tts.edgeUnavailableNote"] = "Edge neural niedostępny — używam systemowego",
        ["tts.chunkProgress"] = "{0} {1}/{2}",
        ["tts.engineEdge"] = "Edge",
        ["tts.engineSystem"] = "System",
        ["tts.engineFallback"] = "System (Edge↓)",
    };
}
